from __future__ import annotations

from core.pattern import GhostSettings, InstrumentConfig


INSTRUMENT_ORDER = [
    "kick",
    "snare",
    "hihat_closed",
    "hihat_open",
    "ride",
    "crash",
    "tom_high",
    "tom_mid",
    "tom_low",
]


def build_default_instruments() -> dict[str, InstrumentConfig]:
    return {
        "kick": InstrumentConfig(
            key="kick",
            name="Kick",
            midi_note=36,
            density=0.45,
            velocity_min=64,
            velocity_max=98,
            syncopation_amount=0.35,
            timing_feel="neutral",
            repetition_vs_variation=0.68,
        ),
        "snare": InstrumentConfig(
            key="snare",
            name="Snare",
            midi_note=38,
            density=0.4,
            velocity_min=58,
            velocity_max=94,
            syncopation_amount=0.15,
            timing_feel="neutral",
            repetition_vs_variation=0.84,
            ghost_settings=GhostSettings(
                enabled=True,
                density=0.28,
                velocity=33,
                timing_offset_amount=9,
                max_distance_from_anchor=2,
                placement="both",
            ),
        ),
        "hihat_closed": InstrumentConfig(
            key="hihat_closed",
            name="Hi-Hat Closed",
            midi_note=42,
            density=0.85,
            pulse_division="sixteenth",
            pulse_space=0.0,
            velocity_min=62,
            velocity_max=92,
            syncopation_amount=0.08,
            timing_feel="neutral",
            repetition_vs_variation=0.9,
            ghost_settings=GhostSettings(
                enabled=True,
                density=0.18,
                velocity=27,
                timing_offset_amount=7,
                max_distance_from_anchor=1,
                placement="after",
            ),
        ),
        "hihat_open": InstrumentConfig(
            key="hihat_open",
            name="Hi-Hat Open",
            midi_note=46,
            density=0.18,
            velocity_min=48,
            velocity_max=76,
            allowed_slots="",
            syncopation_amount=0.0,
            repetition_vs_variation=0.5,
        ),
        "ride": InstrumentConfig(
            key="ride",
            name="Ride",
            midi_note=51,
            density=0.7,
            pulse_division="eighth",
            pulse_space=0.0,
            velocity_min=46,
            velocity_max=74,
            syncopation_amount=0.12,
            timing_feel="neutral",
            repetition_vs_variation=0.78,
            ghost_settings=GhostSettings(
                enabled=True,
                density=0.12,
                velocity=29,
                timing_offset_amount=6,
                max_distance_from_anchor=1,
                placement="after",
            ),
        ),
        "crash": InstrumentConfig(
            key="crash",
            name="Crash",
            midi_note=49,
            density=0.12,
            velocity_min=76,
            velocity_max=92,
            syncopation_amount=0.0,
            repetition_vs_variation=0.4,
        ),
        "tom_high": InstrumentConfig(
            key="tom_high",
            name="Tom High",
            midi_note=50,
            enabled=False,
            tom_hit_count=0,
            density=0.12,
            velocity_min=54,
            velocity_max=86,
            syncopation_amount=0.22,
            repetition_vs_variation=0.36,
        ),
        "tom_mid": InstrumentConfig(
            key="tom_mid",
            name="Tom Mid",
            midi_note=47,
            enabled=False,
            tom_hit_count=0,
            density=0.12,
            velocity_min=54,
            velocity_max=86,
            syncopation_amount=0.22,
            repetition_vs_variation=0.36,
        ),
        "tom_low": InstrumentConfig(
            key="tom_low",
            name="Tom Low",
            midi_note=45,
            enabled=False,
            tom_hit_count=0,
            density=0.12,
            velocity_min=54,
            velocity_max=86,
            syncopation_amount=0.22,
            repetition_vs_variation=0.36,
        ),
    }
